-- MySQL Script generated by MySQL Workbench
-- Sat May 20 05:50:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sedt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sedt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sedt` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sedt` ;

-- -----------------------------------------------------
-- Table `sedt`.`objetivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sedt`.`objetivos` (
  `idobjetivos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `inicio` VARCHAR(45) NOT NULL,
  `fin` VARCHAR(45) NOT NULL,
  `puntaje` VARCHAR(45) NOT NULL,
  `id_trabajador` INT NULL DEFAULT NULL,
  `avance` FLOAT NULL DEFAULT '0',
  PRIMARY KEY (`idobjetivos`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sedt`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sedt`.`trabajador` (
  `idtrabajador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtrabajador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
